#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sun May 12 21:23:33 2024
#

import wx
import ClasesFunciones

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

def generar_cartas():
    m = []
    for i in range(52):
        img = wx.Bitmap()
        img.LoadFile(f"Imagenes//Cartas//{i}.png")
        m.append(img)
    return m

class Ventana(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1296, 696))
        self.SetTitle("BlackJack")

        sizer_general = wx.BoxSizer(wx.HORIZONTAL)

        sizer_col_estatica = wx.BoxSizer(wx.VERTICAL)
        sizer_general.Add(sizer_col_estatica, 0, wx.EXPAND, 0)

        sizer_modo_juego = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Modo de Juego"), wx.HORIZONTAL)
        sizer_col_estatica.Add(sizer_modo_juego, 0, wx.ALL | wx.EXPAND, 10)

        self.boton_manual = wx.RadioButton(self, wx.ID_ANY, "Manual", style=wx.RB_GROUP)
        self.boton_manual.SetValue(1)
        sizer_modo_juego.Add(self.boton_manual, 0, wx.RIGHT, 10)

        self.boton_automatico = wx.RadioButton(self, wx.ID_ANY, "Automatico", style=wx.RB_GROUP)
        sizer_modo_juego.Add(self.boton_automatico, 0, wx.LEFT, 10)

        sizer_retardo = wx.BoxSizer(wx.HORIZONTAL)
        sizer_col_estatica.Add(sizer_retardo, 0, wx.ALL | wx.EXPAND, 10)

        txt_retardo = wx.StaticText(self, wx.ID_ANY, "Retardo: ")
        sizer_retardo.Add(txt_retardo, 0, wx.TOP, 5)

        self.retardo = wx.TextCtrl(self, wx.ID_ANY, "25\n", style=wx.TE_RIGHT)
        self.retardo.SetMinSize((60, 20))
        sizer_retardo.Add(self.retardo, 0, 0, 0)

        txt_ms = wx.StaticText(self, wx.ID_ANY, " ms.")
        sizer_retardo.Add(txt_ms, 0, wx.TOP, 5)

        sizer_accion = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Accion"), wx.VERTICAL)
        sizer_col_estatica.Add(sizer_accion, 0, wx.ALL | wx.EXPAND, 10)

        self.boton_pedir = wx.Button(self, wx.ID_ANY, "Pedir")
        self.boton_pedir.SetMinSize((100, 25))
        self.boton_pedir.Enable(False)
        sizer_accion.Add(self.boton_pedir, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 3)

        self.boton_cerrar = wx.Button(self, wx.ID_ANY, "Cerrar")
        self.boton_cerrar.SetMinSize((186, 25))
        self.boton_cerrar.Enable(False)
        sizer_accion.Add(self.boton_cerrar, 0, wx.ALL | wx.EXPAND, 0)

        self.boton_doblar = wx.Button(self, wx.ID_ANY, "Doblar")
        self.boton_doblar.SetMinSize((186, 25))
        self.boton_doblar.Enable(False)
        sizer_accion.Add(self.boton_doblar, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 3)

        self.boton_separar = wx.Button(self, wx.ID_ANY, "Separar")
        self.boton_separar.SetMinSize((186, 25))
        self.boton_separar.Enable(False)
        sizer_accion.Add(self.boton_separar, 0, wx.ALL | wx.EXPAND, 0)

        sizer_conteos = wx.BoxSizer(wx.VERTICAL)
        sizer_col_estatica.Add(sizer_conteos, 0, wx.EXPAND, 10)

        sizer_num_partida = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Partida"), wx.HORIZONTAL)
        sizer_conteos.Add(sizer_num_partida, 0, wx.ALL | wx.EXPAND, 5)

        numero_partida = wx.StaticText(self, wx.ID_ANY, "1", style=wx.ALIGN_CENTER_HORIZONTAL)
        numero_partida.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_num_partida.Add(numero_partida, 1, wx.ALL, 0)

        sizer_balance_partida = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Balance Partida"), wx.HORIZONTAL)
        sizer_conteos.Add(sizer_balance_partida, 1, wx.ALL | wx.EXPAND, 5)

        balance_partida = wx.StaticText(self, wx.ID_ANY, "0", style=wx.ALIGN_CENTER_HORIZONTAL)
        balance_partida.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_balance_partida.Add(balance_partida, 1, wx.ALL, 0)

        sizer_balance_total = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Balance Total"), wx.HORIZONTAL)
        sizer_conteos.Add(sizer_balance_total, 1, wx.ALL | wx.EXPAND, 5)

        balance_total = wx.StaticText(self, wx.ID_ANY, "0", style=wx.ALIGN_CENTER_HORIZONTAL)
        balance_total.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_balance_total.Add(balance_total, 1, wx.ALL, 0)

        sizer_tiempo = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Tiempo"), wx.HORIZONTAL)
        sizer_conteos.Add(sizer_tiempo, 1, wx.ALL | wx.EXPAND, 5)

        tiempo = wx.StaticText(self, wx.ID_ANY, "10", style=wx.ALIGN_CENTER_HORIZONTAL)
        tiempo.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_tiempo.Add(tiempo, 1, wx.ALL, 0)

        #Panel dinamico (Manos)

        self.panel_dinamico = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_dinamico.SetScrollRate(10, 10)
        sizer_general.Add(self.panel_dinamico, 1, wx.EXPAND, 0)

        sizer_manos_generales = wx.BoxSizer(wx.VERTICAL)

        #Aqui se generan los BoxSizer para las diferentes manos
        self.sizer_croupier = wx.BoxSizer(wx.HORIZONTAL)
        sizer_manos_generales.Add(self.sizer_croupier, 0, wx.EXPAND, 0)

        self.sizer_jugador = wx.BoxSizer(wx.HORIZONTAL)
        sizer_manos_generales.Add(self.sizer_jugador, 0, wx.EXPAND, 0)

        self.panel_dinamico.SetSizer(sizer_manos_generales)

        self.SetSizer(sizer_general)

        self.Layout()
        # end wxGlade

# end of class Ventana

class BlackJack(wx.App):
    def OnInit(self):
        self.frame = Ventana(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class BlackJack
def main():
    app = BlackJack(0)
    cartas = []
    cartas = generar_cartas()

    #Quiero crear un bitmap en la ventana
    # Crear un bitmap con la primera carta de la lista de cartas
    carta_bitmap = wx.StaticBitmap(app.frame.panel_dinamico, wx.ID_ANY, cartas[0])
    carta_bitmap_2 = wx.StaticBitmap(app.frame.panel_dinamico, wx.ID_ANY, cartas[1])
    carta_bitmap_3 = wx.StaticBitmap(app.frame.panel_dinamico, wx.ID_ANY, cartas[1])

    # Agregar el bitmap al sizer correspondiente en la ventana (por ejemplo, sizer_croupier)
    app.frame.sizer_croupier.Add(carta_bitmap, 0, wx.ALL, 5)
    app.frame.sizer_croupier.Add(carta_bitmap_2, 0, wx.ALL, 5)
    app.frame.sizer_jugador.Add(carta_bitmap_3, 0, wx.ALL, 5)

    # Asegúrate de llamar a Layout() para que los cambios en el diseño se reflejen
    app.frame.Layout()
    app.MainLoop()


if __name__ == "__main__":
    main()
